name: CI

on:
  pull_request:

jobs:
  tofu:
    name: OpenTofu
    uses: ./.github/workflows/tofu.yml
    secrets: inherit

  ansible:
    name: Ansible
    uses: ./.github/workflows/ansible.yml
    secrets: inherit
