name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  opentofu:
    name: OpenTofu
    uses: ./.github/workflows/tofu.yml
    secrets:
      SOPS_AGE_KEY: ${{ secrets.AGE_SECRET_KEY }}
