name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  opentofu:
    name: OpenTofu
    uses: ./.github/workflows/tofu.yml
    secrets: inherit
    with:
      apply_enabled: ${{ github.event.name == 'push' && github.ref == 'refs/heads/master' }}
